@api=http://localhost:3000/api
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjIzNTI1MDQzLCJleHAiOjE2MzEzMDEwNDN9.o8pTAA_JXE5zE_xJlt4wi6bz6E4YRMmFIrqg13yCAvg


# Auth apis

###
# Signup new user
POST {{api}}/auth/signup
Content-Type: application/json

{
  "name": "James Gosling",
  "email": "james@example.com",
  "password": "test1234",
  "password_confirm": "test1234"
}

###
# Login user
POST {{api}}/auth/login
Content-Type: application/json

{
  "email": "admin@projectorv2.io",
  "password": "test1234"
}


# User apis

###
# Get all users
GET {{api}}/users

###3
# Get user by id
GET {{api}}/users/1

###
# Create new user
POST {{api}}/users
Content-Type: application/json

{
  "name": "user10",
  "email": "user10@projectorv2.io",
  "password": "test1234",
  "password_confirm": "test1234"
}

###
# Update user
PUT {{api}}/users/21
Content-Type: application/json

{
  "name": "user21",
  "email": "user21@projectorv2.io"
}

###
# Delete user
DELETE {{api}}/users/21




# Post apis

###
# Get all posts
GET {{api}}/posts

###
# Get post by id
GET {{api}}/posts/1

###
# Create new post
POST {{api}}/posts
Content-Type: application/json

{
  "name": "post14",
  "summary": "post 14 summary",
  "description": "post 14 description",
  "user": "1"
}

###
# Update post
PUT {{api}}/posts/7
Content-Type: application/json

{
  "name": "post7",
  "summary": "post 7 summary",
  "description": "post 7 very long description"
}

###
# Delete post
DELETE {{api}}/posts/7



# Comment apis

###
# Get all comments related to a post
GET {{api}}/posts/6/comments

###
# Create new comment
POST {{api}}/posts/6/comments
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "comment": "New comment from admin for post 6"
}

###
# Get all comments
GET {{api}}/comments

###
# Get comment by id
GET {{api}}/comments/f3bd90a0-7206-4539-9faa-d6429c32659b

###
# Update comment
PUT {{api}}/comments/f3bd90a0-7206-4539-9faa-d6429c32659b
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "comment": "New edited comment from admin for post 6"
}

###
# Delete comment
DELETE {{api}}/comments/f3bd90a0-7206-4539-9faa-d6429c32659b
Authorization: Bearer {{token}}

